theme: jekyll-theme-minimal

title: NAScontrol
description: A NAS control project
logo: https://github.com/eurovibes/nascontrol/raw/master/images/nascontrol.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
